// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OutilRentabilite.Data;

#nullable disable

namespace OutilRentabilite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OutilRentabilite.Models.ActionProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MinutesParAction")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<decimal>("NombreActions")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("ProduitFinancierId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("ProduitFinancierId");

                    b.ToTable("ActionsProduits");
                });

            modelBuilder.Entity("OutilRentabilite.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AideScolaire")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Assiduite")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Assurance")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Autre")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("CNaPS")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("CSR")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Caisse")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Carburant")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("ComplementSalaire")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Entretien")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Fonction")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("FraisMedicaux")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Gratification")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("HeuresDisponiblesParAn")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("IndemniteBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Logement")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<decimal>("OSIE")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Representation")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Responsabilite")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Restauration")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("SocialEntretien")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Technicite")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Telephone")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("TicketsPPN")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Transport")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("VoitureAmortissement")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("WU")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ParametresGenerauxProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bordereau")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Communication")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Informatique")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("LivretPa")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("ProduitFinancierId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitFinancierId")
                        .IsUnique();

                    b.ToTable("ParametresGenerauxProduits");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ParametresSimulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoutFinancement")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("CoutOperationnel")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("CoutRisque")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<DateTime>("DateSimulation")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DureeMois")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("FondsPropres")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("FraisDossier")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("FraisGestion")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<int>("NombreOffre")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProduitFinancierId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<float>("TauxInteret")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<decimal>("TotalActif")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitFinancierId");

                    b.ToTable("ParametresSimulations");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ProduitFinancier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TypeProduit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ProduitsFinanciers");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ResultatCalcul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoutUnitairePartiel")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<DateTime>("DateCalcul")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ProduitFinancierId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitFinancierId");

                    b.ToTable("ResultatCalculs");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ResultatSimulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BeneficeNet")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("CoutTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<float>("MargeBrute")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("MargeNette")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("ParametresSimulationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("PaybackPeriod")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<float>("ROA")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("ROE")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("ROI")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<decimal>("RevenuTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ParametresSimulationId")
                        .IsUnique();

                    b.ToTable("ResultatsSimulations");
                });

            modelBuilder.Entity("OutilRentabilite.Models.TauxMarche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bta180")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Bta30")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Bta360")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Bta90")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<DateTime>("DateEnregistrement")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("Marge")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("Refinancement")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("ReserveObligatoire")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("TauxIRCM")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("TauxInteret")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("TauxPlacementJourLeJour")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)");

                    b.HasKey("Id");

                    b.ToTable("TauxMarches");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ActionProduit", b =>
                {
                    b.HasOne("OutilRentabilite.Models.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutilRentabilite.Models.ProduitFinancier", "ProduitFinancier")
                        .WithMany("Actions")
                        .HasForeignKey("ProduitFinancierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("ProduitFinancier");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ParametresGenerauxProduit", b =>
                {
                    b.HasOne("OutilRentabilite.Models.ProduitFinancier", "ProduitFinancier")
                        .WithOne("ParametresGenerauxProduit")
                        .HasForeignKey("OutilRentabilite.Models.ParametresGenerauxProduit", "ProduitFinancierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduitFinancier");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ParametresSimulation", b =>
                {
                    b.HasOne("OutilRentabilite.Models.ProduitFinancier", "ProduitFinancier")
                        .WithMany("Simulations")
                        .HasForeignKey("ProduitFinancierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduitFinancier");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ResultatCalcul", b =>
                {
                    b.HasOne("OutilRentabilite.Models.ProduitFinancier", "ProduitFinancier")
                        .WithMany("Resultats")
                        .HasForeignKey("ProduitFinancierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduitFinancier");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ResultatSimulation", b =>
                {
                    b.HasOne("OutilRentabilite.Models.ParametresSimulation", "parametresSimulation")
                        .WithOne("Resultat")
                        .HasForeignKey("OutilRentabilite.Models.ResultatSimulation", "ParametresSimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parametresSimulation");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ParametresSimulation", b =>
                {
                    b.Navigation("Resultat");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ProduitFinancier", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("ParametresGenerauxProduit");

                    b.Navigation("Resultats");

                    b.Navigation("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
