// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OutilRentabilite.Data;

#nullable disable

namespace OutilRentabilite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OutilRentabilite.Models.ParametresSimulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoutFinancement")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("CoutOperationnel")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("CoutRisque")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("DateSimulation")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DureeMois")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("FondsPropres")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("FraisDossier")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("FraisGestion")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("NombreOffre")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProduitFinancierId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<float>("TauxInteret")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<decimal>("TotalActif")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitFinancierId");

                    b.ToTable("ParametresSimulations");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ProduitFinancier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TypeProduit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ProduitsFinanciers");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ResultatSimulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BeneficeNet")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("CoutTotal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<float>("MargeBrute")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("MargeNette")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("ParametresSimulationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("PaybackPeriod")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<float>("ROA")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("ROE")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("ROI")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<decimal>("RevenuTotal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ParametresSimulationId")
                        .IsUnique();

                    b.ToTable("ResultatsSimulations");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ParametresSimulation", b =>
                {
                    b.HasOne("OutilRentabilite.Models.ProduitFinancier", "ProduitFinancier")
                        .WithMany("Simulations")
                        .HasForeignKey("ProduitFinancierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduitFinancier");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ResultatSimulation", b =>
                {
                    b.HasOne("OutilRentabilite.Models.ParametresSimulation", "parametresSimulation")
                        .WithOne("Resultat")
                        .HasForeignKey("OutilRentabilite.Models.ResultatSimulation", "ParametresSimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parametresSimulation");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ParametresSimulation", b =>
                {
                    b.Navigation("Resultat");
                });

            modelBuilder.Entity("OutilRentabilite.Models.ProduitFinancier", b =>
                {
                    b.Navigation("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
